// import "./globals.css";
// import { Inter } from "next/font/google";
import themes from "@actionishope/shelley/styles";
import { Toolbar } from "@actionishope/shelley/Toolbar";
import { Button } from "@actionishope/shelley/Button";
import Link from "next/link";
import { ElementType } from "react";
import { Nav } from "../components/Nav";
import { st, classes } from "../theme/main.st.css";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={themes.shelley}>
      <body>
        <Toolbar className={classes.header}>
          <Button as={Link as ElementType} href="/button">
            Button
          </Button>
        </Toolbar>
        <Nav
          className={st(classes.nav, {
            isVisible: true,
          })}
        />
        <main className={classes.main}>{children}</main>
      </body>
    </html>
  );
}
